# Generated by Django 4.2.11 on 2024-03-28 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_index_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprosperityindexdata',
            name='real_estate_taxes_by_mortage',
        ),
        migrations.AddField(
            model_name='healthprosperityindexdata',
            name='health_care_insurance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprosperityindexdata',
            name='real_estate_taxes_by_mortgage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='child_mortality_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='employment_total_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='household_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='severe_housing_problem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='working_average_wage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='working_total_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprosperityindexdata',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
